var express = require('express');
var router = express.Router();

/* GET reviews. */
router.get('/', function(req, res, next) {
  res.json(reviews);
});


reviews = [
    {
      "id": 1,
      "course_id": 18,
      "teacher_id": 33,
      "quality": 2,
      "difficulty": 5,
      "can_recommend": 1,
      "worth_credits": 3,
      "books_req": 1,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Cotinus Mill.",
      "teacher_review": "Smoketree"
    },
    {
      "id": 2,
      "course_id": 1,
      "teacher_id": 24,
      "quality": 5,
      "difficulty": 4,
      "can_recommend": 0,
      "worth_credits": 4,
      "books_req": 1,
      "percentage_mand": 1,
      "exam": 0,
      "course_review": "Dicksonia squarrosa (G. Forst.) Sw.",
      "teacher_review": "Hard Treefern"
    },
    {
      "id": 3,
      "course_id": 30,
      "teacher_id": 22,
      "quality": 4,
      "difficulty": 2,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 1,
      "exam": 0,
      "course_review": "Chamaesyce dioica (Kunth) Millsp.",
      "teacher_review": "Royal Sandmat"
    },
    {
      "id": 4,
      "course_id": 6,
      "teacher_id": 35,
      "quality": 1,
      "difficulty": 2,
      "can_recommend": 1,
      "worth_credits": 3,
      "books_req": 1,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Valerianella umbilicata (Sull.) Alph. Wood",
      "teacher_review": "Navel Cornsalad"
    },
    {
      "id": 5,
      "course_id": 27,
      "teacher_id": 30,
      "quality": 3,
      "difficulty": 2,
      "can_recommend": 0,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 2,
      "exam": 1,
      "course_review": "Taraxacum lyratum (Ledeb.) DC.",
      "teacher_review": "Harp Dandelion"
    },
    {
      "id": 6,
      "course_id": 28,
      "teacher_id": 30,
      "quality": 2,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 1,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Halimodendron Fisch. ex DC.",
      "teacher_review": "Halimodendron"
    },
    {
      "id": 7,
      "course_id": 28,
      "teacher_id": 25,
      "quality": 5,
      "difficulty": 5,
      "can_recommend": 0,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 0,
      "course_review": "Suaeda calceoliformis (Hook.) Moq.",
      "teacher_review": "Pursh Seepweed"
    },
    {
      "id": 8,
      "course_id": 22,
      "teacher_id": 19,
      "quality": 3,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 4,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 0,
      "course_review": "Ipomoea pauciflora M. Martens & Galeotti",
      "teacher_review": "Tree Morning Glory"
    },
    {
      "id": 9,
      "course_id": 13,
      "teacher_id": 11,
      "quality": 2,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 2,
      "exam": 0,
      "course_review": "Jacaranda Juss.",
      "teacher_review": "Jacaranda"
    },
    {
      "id": 10,
      "course_id": 3,
      "teacher_id": 37,
      "quality": 2,
      "difficulty": 1,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 4,
      "exam": 0,
      "course_review": "Carex specicola J.T. Howell",
      "teacher_review": "Navajo Sedge"
    },
    {
      "id": 11,
      "course_id": 17,
      "teacher_id": 23,
      "quality": 2,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Leptogium contortum Sierk",
      "teacher_review": "Contorted Skin Lichen"
    },
    {
      "id": 12,
      "course_id": 3,
      "teacher_id": 43,
      "quality": 5,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 1,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 0,
      "course_review": "Calystegia macrostegia (Greene) Brummitt ssp. arida (Greene) Brummitt",
      "teacher_review": "Island False Bindweed"
    },
    {
      "id": 13,
      "course_id": 18,
      "teacher_id": 21,
      "quality": 3,
      "difficulty": 3,
      "can_recommend": 0,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Helianthella californica A. Gray ssp. californica",
      "teacher_review": "California Helianthella"
    },
    {
      "id": 14,
      "course_id": 18,
      "teacher_id": 16,
      "quality": 3,
      "difficulty": 3,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 0,
      "course_review": "Gyroweisia Schimp.",
      "teacher_review": "Gyroweisia Moss"
    },
    {
      "id": 15,
      "course_id": 27,
      "teacher_id": 28,
      "quality": 5,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Paraserianthes I.C. Nielsen",
      "teacher_review": "Paraserianthes"
    },
    {
      "id": 16,
      "course_id": 21,
      "teacher_id": 43,
      "quality": 5,
      "difficulty": 5,
      "can_recommend": 0,
      "worth_credits": 2,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Oligotrichum hercynicum (Hedw.) Lam. & DC.",
      "teacher_review": "Oligotrichum Moss"
    },
    {
      "id": 17,
      "course_id": 27,
      "teacher_id": 35,
      "quality": 3,
      "difficulty": 5,
      "can_recommend": 0,
      "worth_credits": 4,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Eriogonum heermannii Durand & Hilg. var. floccosum Munz",
      "teacher_review": "Clark Mountain Buckwheat"
    },
    {
      "id": 18,
      "course_id": 30,
      "teacher_id": 13,
      "quality": 4,
      "difficulty": 4,
      "can_recommend": 0,
      "worth_credits": 1,
      "books_req": 0,
      "percentage_mand": 1,
      "exam": 0,
      "course_review": "Scutellaria elliptica Muhl. ex Spreng. var. elliptica",
      "teacher_review": "Hairy Skullcap"
    },
    {
      "id": 19,
      "course_id": 16,
      "teacher_id": 37,
      "quality": 3,
      "difficulty": 3,
      "can_recommend": 0,
      "worth_credits": 3,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 0,
      "course_review": "Tradescantia subacaulis Bush",
      "teacher_review": "Stemless Spiderwort"
    },
    {
      "id": 20,
      "course_id": 20,
      "teacher_id": 21,
      "quality": 1,
      "difficulty": 5,
      "can_recommend": 0,
      "worth_credits": 1,
      "books_req": 0,
      "percentage_mand": 1,
      "exam": 1,
      "course_review": "Penstemon calycosus Small",
      "teacher_review": "Longsepal Beardtongue"
    },
    {
      "id": 21,
      "course_id": 26,
      "teacher_id": 24,
      "quality": 5,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Hedeoma diffusa Greene",
      "teacher_review": "Spreading False Pennyroyal"
    },
    {
      "id": 22,
      "course_id": 16,
      "teacher_id": 24,
      "quality": 4,
      "difficulty": 2,
      "can_recommend": 0,
      "worth_credits": 1,
      "books_req": 1,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Astragalus miser Douglas ex Hook. var. crispatus (M.E. Jones) Cronquist",
      "teacher_review": "Timber Milkvetch"
    },
    {
      "id": 23,
      "course_id": 20,
      "teacher_id": 5,
      "quality": 3,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 2,
      "exam": 1,
      "course_review": "Helianthella californica A. Gray ssp. californica",
      "teacher_review": "California Helianthella"
    },
    {
      "id": 24,
      "course_id": 3,
      "teacher_id": 29,
      "quality": 4,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Draba aureola S. Watson",
      "teacher_review": "Mt. Lassen Draba"
    },
    {
      "id": 25,
      "course_id": 15,
      "teacher_id": 47,
      "quality": 2,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 1,
      "percentage_mand": 1,
      "exam": 0,
      "course_review": "Bryoria friabilis Brodo & D. Hawksw.",
      "teacher_review": "Horsehair Lichen"
    },
    {
      "id": 26,
      "course_id": 22,
      "teacher_id": 47,
      "quality": 4,
      "difficulty": 4,
      "can_recommend": 0,
      "worth_credits": 2,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Hordeum jubatum L. ssp. jubatum",
      "teacher_review": "Foxtail Barley"
    },
    {
      "id": 27,
      "course_id": 29,
      "teacher_id": 14,
      "quality": 2,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Sabatia dodecandra (L.) Britton, Sterns & Poggenb.",
      "teacher_review": "Marsh Rose Gentian"
    },
    {
      "id": 28,
      "course_id": 3,
      "teacher_id": 39,
      "quality": 4,
      "difficulty": 2,
      "can_recommend": 1,
      "worth_credits": 3,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Psorotichia segregata (Nyl.) Hasse",
      "teacher_review": "Psorotichia Lichen"
    },
    {
      "id": 29,
      "course_id": 16,
      "teacher_id": 43,
      "quality": 1,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 4,
      "books_req": 0,
      "percentage_mand": 1,
      "exam": 1,
      "course_review": "Pleurochaete Lindb.",
      "teacher_review": "Pleurochaete Moss"
    },
    {
      "id": 30,
      "course_id": 14,
      "teacher_id": 27,
      "quality": 2,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 4,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Rumex pulcher L.",
      "teacher_review": "Fiddle Dock"
    },
    {
      "id": 31,
      "course_id": 24,
      "teacher_id": 30,
      "quality": 4,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 0,
      "percentage_mand": 1,
      "exam": 1,
      "course_review": "Betula platyphylla Sukaczev",
      "teacher_review": "Asian White Birch"
    },
    {
      "id": 32,
      "course_id": 17,
      "teacher_id": 8,
      "quality": 2,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Trypethelium virens Tuck. ex Michener",
      "teacher_review": "Trypelthelium Lichen"
    },
    {
      "id": 33,
      "course_id": 17,
      "teacher_id": 42,
      "quality": 5,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Rubus lasiococcus A. Gray",
      "teacher_review": "Roughfruit Berry"
    },
    {
      "id": 34,
      "course_id": 23,
      "teacher_id": 17,
      "quality": 1,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 1,
      "exam": 1,
      "course_review": "Cryptantha micrantha (Torr.) I.M. Johnst. var. micrantha",
      "teacher_review": "Redroot Cryptantha"
    },
    {
      "id": 35,
      "course_id": 10,
      "teacher_id": 14,
      "quality": 2,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 1,
      "exam": 0,
      "course_review": "Agastache parvifolia Eastw.",
      "teacher_review": "Smallleaf Giant Hyssop"
    },
    {
      "id": 36,
      "course_id": 24,
      "teacher_id": 21,
      "quality": 1,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Chaenactis xantiana A. Gray",
      "teacher_review": "Fleshcolor Pincushion"
    },
    {
      "id": 37,
      "course_id": 24,
      "teacher_id": 33,
      "quality": 1,
      "difficulty": 2,
      "can_recommend": 1,
      "worth_credits": 4,
      "books_req": 0,
      "percentage_mand": 1,
      "exam": 1,
      "course_review": "Astragalus canadensis L. var. mortonii (Nutt.) S. Watson",
      "teacher_review": "Morton's Canadian Milkvetch"
    },
    {
      "id": 38,
      "course_id": 7,
      "teacher_id": 42,
      "quality": 1,
      "difficulty": 5,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 0,
      "course_review": "Quercus ilex L.",
      "teacher_review": "Holly Oak"
    },
    {
      "id": 39,
      "course_id": 7,
      "teacher_id": 38,
      "quality": 4,
      "difficulty": 4,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 2,
      "exam": 1,
      "course_review": "Celtis australis L.",
      "teacher_review": "European Hackberry"
    },
    {
      "id": 40,
      "course_id": 20,
      "teacher_id": 45,
      "quality": 2,
      "difficulty": 5,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 0,
      "percentage_mand": 2,
      "exam": 0,
      "course_review": "Lilium washingtonianum Kellogg ssp. purpurascens (Stearn) M.W. Skinner",
      "teacher_review": "Cascade Lily"
    },
    {
      "id": 41,
      "course_id": 28,
      "teacher_id": 20,
      "quality": 5,
      "difficulty": 1,
      "can_recommend": 1,
      "worth_credits": 1,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Rhynchospora corniculata (Lam.) A. Gray",
      "teacher_review": "Shortbristle Horned Beaksedge"
    },
    {
      "id": 42,
      "course_id": 20,
      "teacher_id": 42,
      "quality": 3,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 0,
      "percentage_mand": 2,
      "exam": 0,
      "course_review": "Ceanothus connivens Greene",
      "teacher_review": "Trailing Buckbrush"
    },
    {
      "id": 43,
      "course_id": 26,
      "teacher_id": 38,
      "quality": 2,
      "difficulty": 2,
      "can_recommend": 1,
      "worth_credits": 1,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 0,
      "course_review": "Spartina alterniflora Loisel.",
      "teacher_review": "Smooth Cordgrass"
    },
    {
      "id": 44,
      "course_id": 7,
      "teacher_id": 11,
      "quality": 2,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 1,
      "percentage_mand": 1,
      "exam": 0,
      "course_review": "Platanthera lacera (Michx.) G. Don",
      "teacher_review": "Green Fringed Orchid"
    },
    {
      "id": 45,
      "course_id": 28,
      "teacher_id": 45,
      "quality": 1,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 1,
      "books_req": 1,
      "percentage_mand": 4,
      "exam": 0,
      "course_review": "Polemonium foliosissimum A. Gray var. molle (Greene) Anway",
      "teacher_review": "Towering Jacob's-ladder"
    },
    {
      "id": 46,
      "course_id": 4,
      "teacher_id": 28,
      "quality": 4,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 2,
      "books_req": 0,
      "percentage_mand": 2,
      "exam": 1,
      "course_review": "Eucladium verticillatum (Brid.) Bruch & Schimp.",
      "teacher_review": "Eucladium Moss"
    },
    {
      "id": 47,
      "course_id": 13,
      "teacher_id": 16,
      "quality": 4,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 1,
      "percentage_mand": 2,
      "exam": 1,
      "course_review": "Urochloa mutica (Forssk.) T.Q. Nguyen",
      "teacher_review": "Para Grass"
    },
    {
      "id": 48,
      "course_id": 12,
      "teacher_id": 21,
      "quality": 2,
      "difficulty": 4,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Isopogon R. Br. ex Knight",
      "teacher_review": "Cone Flower"
    },
    {
      "id": 49,
      "course_id": 30,
      "teacher_id": 27,
      "quality": 5,
      "difficulty": 1,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Ceanothus ×vanrensselaeri J.B. Roof",
      "teacher_review": "Ceanothus"
    },
    {
      "id": 50,
      "course_id": 4,
      "teacher_id": 3,
      "quality": 4,
      "difficulty": 5,
      "can_recommend": 1,
      "worth_credits": 1,
      "books_req": 0,
      "percentage_mand": 4,
      "exam": 1,
      "course_review": "Erigeron peregrinus (Banks ex Pursh) Greene ssp. peregrinus",
      "teacher_review": "Subalpine Fleabane"
    },
    {
      "id": 51,
      "course_id": 6,
      "teacher_id": 17,
      "quality": 4,
      "difficulty": 1,
      "can_recommend": 1,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 4,
      "exam": 1,
      "course_review": "Pterostegia Fisch. & C.A. Mey.",
      "teacher_review": "Pterostegia"
    },
    {
      "id": 52,
      "course_id": 28,
      "teacher_id": 4,
      "quality": 4,
      "difficulty": 1,
      "can_recommend": 1,
      "worth_credits": 1,
      "books_req": 1,
      "percentage_mand": 4,
      "exam": 0,
      "course_review": "Opuntia martiniana (L.D. Benson) Parfitt",
      "teacher_review": "Seashore Cactus"
    },
    {
      "id": 53,
      "course_id": 20,
      "teacher_id": 25,
      "quality": 5,
      "difficulty": 3,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Luzula multiflora (Ehrh.) Lej.",
      "teacher_review": "Common Woodrush"
    },
    {
      "id": 54,
      "course_id": 24,
      "teacher_id": 37,
      "quality": 4,
      "difficulty": 5,
      "can_recommend": 0,
      "worth_credits": 3,
      "books_req": 1,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Plagiopus oederianus (Sw.) H.A. Crum & L.E. Anderson",
      "teacher_review": "Oeder's Plagiopus Moss"
    },
    {
      "id": 55,
      "course_id": 9,
      "teacher_id": 32,
      "quality": 1,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 1,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Lupinus albifrons Benth. var. flumineus C.P. Sm.",
      "teacher_review": "Silver Lupine"
    },
    {
      "id": 56,
      "course_id": 16,
      "teacher_id": 26,
      "quality": 1,
      "difficulty": 5,
      "can_recommend": 0,
      "worth_credits": 4,
      "books_req": 0,
      "percentage_mand": 4,
      "exam": 0,
      "course_review": "Crataegus aemula Beadle",
      "teacher_review": "Rome Hawthorn"
    },
    {
      "id": 57,
      "course_id": 11,
      "teacher_id": 22,
      "quality": 5,
      "difficulty": 1,
      "can_recommend": 1,
      "worth_credits": 1,
      "books_req": 1,
      "percentage_mand": 1,
      "exam": 1,
      "course_review": "Spiranthes vernalis Engelm. & A. Gray",
      "teacher_review": "Spring Lady's Tresses"
    },
    {
      "id": 58,
      "course_id": 10,
      "teacher_id": 7,
      "quality": 2,
      "difficulty": 4,
      "can_recommend": 0,
      "worth_credits": 2,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Brassia caudata (L.) Lindl.",
      "teacher_review": "Cricket Orchid"
    },
    {
      "id": 59,
      "course_id": 21,
      "teacher_id": 24,
      "quality": 1,
      "difficulty": 2,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 0,
      "percentage_mand": 1,
      "exam": 1,
      "course_review": "Nelsonia canescens (Lam.) Spreng.",
      "teacher_review": "Blue Pussyleaf"
    },
    {
      "id": 60,
      "course_id": 24,
      "teacher_id": 10,
      "quality": 1,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Schoenus apogon Roem. & Schult.",
      "teacher_review": "Smooth Bogrush"
    },
    {
      "id": 61,
      "course_id": 18,
      "teacher_id": 50,
      "quality": 4,
      "difficulty": 2,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 1,
      "exam": 1,
      "course_review": "Acalypha mexicana Müll. Arg.",
      "teacher_review": "Mexican Copperleaf"
    },
    {
      "id": 62,
      "course_id": 16,
      "teacher_id": 19,
      "quality": 5,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Pinus parviflora Siebold & Zucc.",
      "teacher_review": "Five-needle Pine"
    },
    {
      "id": 63,
      "course_id": 10,
      "teacher_id": 8,
      "quality": 5,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 3,
      "books_req": 1,
      "percentage_mand": 4,
      "exam": 1,
      "course_review": "Gaillardia multiceps Greene var. microcephala B.L. Turner",
      "teacher_review": "Onion Blanketflower"
    },
    {
      "id": 64,
      "course_id": 1,
      "teacher_id": 37,
      "quality": 3,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 3,
      "books_req": 1,
      "percentage_mand": 2,
      "exam": 0,
      "course_review": "Penstemon fremontii Torr. & A. Gray ex A. Gray var. fremontii",
      "teacher_review": "Fremont's Beardtongue"
    },
    {
      "id": 65,
      "course_id": 23,
      "teacher_id": 49,
      "quality": 1,
      "difficulty": 3,
      "can_recommend": 0,
      "worth_credits": 4,
      "books_req": 0,
      "percentage_mand": 4,
      "exam": 1,
      "course_review": "Garcinia myrtifolia A.C. Sm.",
      "teacher_review": "Garcinia"
    },
    {
      "id": 66,
      "course_id": 23,
      "teacher_id": 47,
      "quality": 2,
      "difficulty": 4,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Silene ×hampeana Meusel & K. Werner",
      "teacher_review": "Catchfly"
    },
    {
      "id": 67,
      "course_id": 27,
      "teacher_id": 2,
      "quality": 2,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Grindelia nuda Alph. Wood var. aphanactis (Rydb.) G.L. Nesom",
      "teacher_review": "Curlytop Gumweed"
    },
    {
      "id": 68,
      "course_id": 9,
      "teacher_id": 35,
      "quality": 3,
      "difficulty": 2,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Rudbeckia heliopsidis Torr. & A. Gray",
      "teacher_review": "Sunfacing Coneflower"
    },
    {
      "id": 69,
      "course_id": 10,
      "teacher_id": 34,
      "quality": 1,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 4,
      "books_req": 0,
      "percentage_mand": 4,
      "exam": 1,
      "course_review": "Bambusa polymorpha Munro",
      "teacher_review": "Polymorph Bamboo"
    },
    {
      "id": 70,
      "course_id": 8,
      "teacher_id": 18,
      "quality": 5,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 1,
      "books_req": 1,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Phyla nodiflora (L.) Greene",
      "teacher_review": "Turkey Tangle Fogfruit"
    },
    {
      "id": 71,
      "course_id": 28,
      "teacher_id": 21,
      "quality": 5,
      "difficulty": 5,
      "can_recommend": 1,
      "worth_credits": 4,
      "books_req": 0,
      "percentage_mand": 2,
      "exam": 1,
      "course_review": "Cladonia borealis S. Stenroos",
      "teacher_review": "Boreal Cup Lichen"
    },
    {
      "id": 72,
      "course_id": 23,
      "teacher_id": 18,
      "quality": 3,
      "difficulty": 5,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 0,
      "percentage_mand": 2,
      "exam": 1,
      "course_review": "Lavatera thuringiaca L.",
      "teacher_review": "Tree Lavatera"
    },
    {
      "id": 73,
      "course_id": 18,
      "teacher_id": 46,
      "quality": 1,
      "difficulty": 4,
      "can_recommend": 0,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 0,
      "course_review": "Navarretia hamata Greene ssp. hamata",
      "teacher_review": "Hooked Pincushionplant"
    },
    {
      "id": 74,
      "course_id": 15,
      "teacher_id": 6,
      "quality": 1,
      "difficulty": 4,
      "can_recommend": 1,
      "worth_credits": 3,
      "books_req": 1,
      "percentage_mand": 4,
      "exam": 1,
      "course_review": "Psiguria pedata (L.) Howard",
      "teacher_review": "Caribbean Pygmymelon"
    },
    {
      "id": 75,
      "course_id": 6,
      "teacher_id": 30,
      "quality": 3,
      "difficulty": 3,
      "can_recommend": 0,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Alocasia brisbanensis (F.M. Bailey) Domin",
      "teacher_review": "Cunjevoi"
    },
    {
      "id": 76,
      "course_id": 3,
      "teacher_id": 20,
      "quality": 5,
      "difficulty": 2,
      "can_recommend": 0,
      "worth_credits": 4,
      "books_req": 0,
      "percentage_mand": 2,
      "exam": 0,
      "course_review": "Hackelia setosa (Piper) I.M. Johnst.",
      "teacher_review": "Bristly Stickseed"
    },
    {
      "id": 77,
      "course_id": 28,
      "teacher_id": 47,
      "quality": 1,
      "difficulty": 3,
      "can_recommend": 0,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 4,
      "exam": 0,
      "course_review": "Ipomopsis congesta (Hook.) V.E. Grant ssp. pseudotypica (Constance & Rollins) Day",
      "teacher_review": "Ballhead Ipomopsis"
    },
    {
      "id": 78,
      "course_id": 9,
      "teacher_id": 27,
      "quality": 4,
      "difficulty": 2,
      "can_recommend": 0,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 4,
      "exam": 0,
      "course_review": "Carex vallicola Dewey var. rusbyi (Mack.) F.J. Herm.",
      "teacher_review": "Rusby's Sedge"
    },
    {
      "id": 79,
      "course_id": 15,
      "teacher_id": 49,
      "quality": 5,
      "difficulty": 4,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 0,
      "course_review": "Eriastrum pluriflorum (A. Heller) H. Mason ssp. pluriflorum",
      "teacher_review": "Tehachapi Woollystar"
    },
    {
      "id": 80,
      "course_id": 12,
      "teacher_id": 14,
      "quality": 5,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 4,
      "books_req": 1,
      "percentage_mand": 2,
      "exam": 1,
      "course_review": "Sclerocactus Britton & Rose",
      "teacher_review": "Fishhook Cactus"
    },
    {
      "id": 81,
      "course_id": 4,
      "teacher_id": 28,
      "quality": 3,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 1,
      "percentage_mand": 2,
      "exam": 0,
      "course_review": "Cryptantha abata I.M. Johnst.",
      "teacher_review": "Dentnut Cryptantha"
    },
    {
      "id": 82,
      "course_id": 23,
      "teacher_id": 29,
      "quality": 1,
      "difficulty": 3,
      "can_recommend": 0,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Phyla ×intermedia Moldenke",
      "teacher_review": "Fogfruit"
    },
    {
      "id": 83,
      "course_id": 10,
      "teacher_id": 8,
      "quality": 1,
      "difficulty": 2,
      "can_recommend": 0,
      "worth_credits": 3,
      "books_req": 1,
      "percentage_mand": 2,
      "exam": 0,
      "course_review": "Spiranthes odorata (Nutt.) Lindl.",
      "teacher_review": "Marsh Lady's Tresses"
    },
    {
      "id": 84,
      "course_id": 13,
      "teacher_id": 35,
      "quality": 4,
      "difficulty": 2,
      "can_recommend": 1,
      "worth_credits": 1,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Rubus particularis L.H. Bailey",
      "teacher_review": "West Virginia Dewberry"
    },
    {
      "id": 85,
      "course_id": 12,
      "teacher_id": 38,
      "quality": 3,
      "difficulty": 5,
      "can_recommend": 1,
      "worth_credits": 4,
      "books_req": 0,
      "percentage_mand": 4,
      "exam": 0,
      "course_review": "Carex ×kenaica Lepage",
      "teacher_review": "Sedge"
    },
    {
      "id": 86,
      "course_id": 12,
      "teacher_id": 20,
      "quality": 4,
      "difficulty": 1,
      "can_recommend": 1,
      "worth_credits": 4,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 0,
      "course_review": "Monolepis nuttalliana (Schult.) Greene",
      "teacher_review": "Nuttall's Povertyweed"
    },
    {
      "id": 87,
      "course_id": 16,
      "teacher_id": 47,
      "quality": 2,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 1,
      "exam": 1,
      "course_review": "Xyris longisepala Kral",
      "teacher_review": "Kral's Yelloweyed Grass"
    },
    {
      "id": 88,
      "course_id": 11,
      "teacher_id": 48,
      "quality": 3,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 1,
      "percentage_mand": 5,
      "exam": 0,
      "course_review": "Celosia L.",
      "teacher_review": "Cock's Comb"
    },
    {
      "id": 89,
      "course_id": 18,
      "teacher_id": 40,
      "quality": 1,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 1,
      "percentage_mand": 4,
      "exam": 1,
      "course_review": "Mertensia longiflora Greene",
      "teacher_review": "Small Bluebells"
    },
    {
      "id": 90,
      "course_id": 4,
      "teacher_id": 23,
      "quality": 2,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 0,
      "percentage_mand": 2,
      "exam": 0,
      "course_review": "Nerium L.",
      "teacher_review": "Oleander"
    },
    {
      "id": 91,
      "course_id": 17,
      "teacher_id": 41,
      "quality": 3,
      "difficulty": 3,
      "can_recommend": 1,
      "worth_credits": 4,
      "books_req": 1,
      "percentage_mand": 4,
      "exam": 1,
      "course_review": "Arthonia gyalectoides Müll. Arg.",
      "teacher_review": "Dot Lichen"
    },
    {
      "id": 92,
      "course_id": 6,
      "teacher_id": 24,
      "quality": 1,
      "difficulty": 5,
      "can_recommend": 0,
      "worth_credits": 4,
      "books_req": 1,
      "percentage_mand": 2,
      "exam": 0,
      "course_review": "Miriquidica deusta (Stenham.) Hertel & Rambold",
      "teacher_review": "Miriquidica Lichen"
    },
    {
      "id": 93,
      "course_id": 27,
      "teacher_id": 38,
      "quality": 4,
      "difficulty": 5,
      "can_recommend": 0,
      "worth_credits": 5,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Bothriochloa hybrida (Gould) Gould",
      "teacher_review": "Hybrid Beardgrass"
    },
    {
      "id": 94,
      "course_id": 27,
      "teacher_id": 31,
      "quality": 5,
      "difficulty": 5,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 2,
      "exam": 0,
      "course_review": "Rinodina dirinoides Zahlbr.",
      "teacher_review": "Rinodina Lichen"
    },
    {
      "id": 95,
      "course_id": 26,
      "teacher_id": 28,
      "quality": 1,
      "difficulty": 5,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 1,
      "percentage_mand": 4,
      "exam": 0,
      "course_review": "Aphanisma blitoides Nutt. ex Moq.",
      "teacher_review": "San Diego Coastalcreeper"
    },
    {
      "id": 96,
      "course_id": 26,
      "teacher_id": 48,
      "quality": 5,
      "difficulty": 2,
      "can_recommend": 1,
      "worth_credits": 5,
      "books_req": 1,
      "percentage_mand": 4,
      "exam": 0,
      "course_review": "Lessingia lemmonii A. Gray var. peirsonii (J.T. Howell) Ferris",
      "teacher_review": "Peirson's Lessingia"
    },
    {
      "id": 97,
      "course_id": 29,
      "teacher_id": 6,
      "quality": 2,
      "difficulty": 1,
      "can_recommend": 1,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 1,
      "exam": 1,
      "course_review": "Digitaria velutina (Forssk.) P. Beauv.",
      "teacher_review": "Velvet Crabgrass"
    },
    {
      "id": 98,
      "course_id": 24,
      "teacher_id": 1,
      "quality": 5,
      "difficulty": 4,
      "can_recommend": 0,
      "worth_credits": 2,
      "books_req": 1,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Cardamine cordifolia A. Gray",
      "teacher_review": "Heartleaf Bittercress"
    },
    {
      "id": 99,
      "course_id": 4,
      "teacher_id": 20,
      "quality": 3,
      "difficulty": 2,
      "can_recommend": 1,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 5,
      "exam": 1,
      "course_review": "Sinocalamus McClure",
      "teacher_review": "Wideleaf Bamboo"
    },
    {
      "id": 100,
      "course_id": 13,
      "teacher_id": 32,
      "quality": 3,
      "difficulty": 1,
      "can_recommend": 0,
      "worth_credits": 3,
      "books_req": 0,
      "percentage_mand": 3,
      "exam": 1,
      "course_review": "Solanum nelsonii Dunal",
      "teacher_review": "Nelson's Horsenettle"
    }
  ];

module.exports = router;
